notes: |
order: 1
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: 7. Verzoeken indienen
    step: Stap 7 van 7
  alert:
    modifier: info
    sronly: "Opmerking:"
    message: |
      We hebben van uw aanvraag meerdere verzoeken gemaakt. Hier ziet u waar u de verzoeken indient.
  form:
    formModifier: form-horizontal
    fieldsets:
    - legend: Verzoek 1
      groups:
      - inputType: static
        label: "Verzoek 1:"
        value: Object Laan van Eik en Duinen 125, 's-Gravenhage 1
        edit: true
      - inputType: static
        label: "Indienen bij:"
        value: Hoogheemraadschap van Delfland
      - inputType: static
        label: "Soort:"
        value: Aanvraag vergunning
      - inputType: static
        label: "Bevat:"
        value: Milieubelastende activiteit - Vergunning (Gemeente)
    - legend: Verzoek 2
      groups:
      - inputType: static
        label: "Verzoek 2:"
        value: Object Laan van Eik en Duinen 125, 's-Gravenhage 1
        edit: true
      - inputType: static
        label: "Indienen bij:"
        value: Gemeente Den Haag
      - inputType: static
        label: "Soort:"
        value: Melding
      - inputType: static
        label: "Bevat:"
        value: Milieubelastende activiteit - Vergunning (Gemeente)
