notes: |
  Toon een contextuele melding aan de gebruiker. Gebasserd op de Bootstrap "Alerts" component.
  Wanneer er een button geplaatst wordt, moet de voorgaande tekst in een `div.dso-rich-content` staan.
status: ready
collated: true
context:
  modifier: alert-success
  message: Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.
variants:
  - name: danger
    context:
      modifier: alert-danger
      message: Dit is een <a href="#">foutmelding</a>. Deze wordt getoond als er iets is misgegaan.
  - name: warning
    context:
      modifier: alert-warning
      message: Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.
  - name: info
    context:
      modifier: alert-info
      message: Dit is een informatiemelding. Deze wordt gebruikt voor <a href="#">aanvullende</a> informatie of tips.
  - name: warning
    context:
      modifier: alert-warning
      message: Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.
      buttontext: Zoekopdracht afbreken
