notes: |
  Pas bij een waarde toont de reset-knop, initieel is deze knop er niet.
status: ready
collated: true
context:
  __title: Zichtbaar label met icoon
  placeholder: Placeholder
  icon: true
  label: Label
variants:
  - name: label-no-icon
    context:
      __title: Zichtbaar label, geen icon
      icon: false
  - name: hidden-label-icon
    context:
      __title: Verborgen label met icon
      hiddenLabel: true
  - name: hidden-label-no-icon
    context:
      __title: verborgen label, geen icon
      hiddenLabel: true
      icon: false
  - name: no-label-icon	
    context:
      __title: Geen label, wel icon	
      label: ""	
  - name: no-label-no-icon	
    context:	
      __title: Geen label, geen icon
      icon: false	
      label: false
  - name: with-value
    context:
      __title: Met waarde
      value: Waarde
      clearButton: true
  - name: hidden-button
    context:
      __title: Verborgen knop
      hideSearchButton: true
  - name: with-results
    context:
      __title: Met resultaten-melding
      hideSearchButton: true
      value: Activiteit
      resultsMessage: 7 activiteiten
  - name: with-hidden-results
    context:
      __title: Met verborgen resultaten-melding
      hideSearchButton: true
      value: Activiteit
      resultsMessage: 7 activiteiten
      resultsHidden: true
