notes: |
  Het accordioncomponent is een lijst met uitklapbare titels. Gebruikers kunnen hiermee delen van content in- en uitklappen. Doordat alleen de titels zichtbaar zijn ziet de gebruiker snel wat belangrijk is om te lezen.

  ## Technische opmerkingen
  Een accordion (`.dso-accordion`) bestaat uit secties (`.dso-accordion-section`). Een sectie heeft een handle (`.dso-section-handle`) en body (`.dso-section-body`).

  Een accordion section in de state "open" moet een `.dso-open` class op `.dso-accordion-section` krijgen. Dit zorgt voor het "chevron-up"-icoon. Ook als het `.dso-accordion-section` element niet in het DOM staat, moet een open accordion altijd `.dso-open` krijgen.

  Er zijn 4 modifiers: `.dso-succes`, `.dso-warning`, `.dso-info` en `.dso-danger` die op de `.dso-accordion-section` kunnen.

  Het is mogelijk om een accordion in een accordion te plaatsen. Er moet dan wel `.dso-nested-accordion` op de `.dso-accordion-section` worden gezet.

  ## Wanneer te gebruiken
  Gebruik een accordion bij lange pagina's met veel content om scrollen te verminderen. De titels vormen voor de gebruiker een informatiestructuur die makkelijk te overzien is. Ook wordt een pagina makkelijker leesbaar als je delen van de content kunt verbergen.

  In sommige gevallen is een accordion beter dan anchors omdat de informatiestructuur behouden blijft. Accordions zijn ook beter bij mobiele weergave, waar de ruimte op de pagina beperkt is.

  ## Wanneer niet te gebruiken
  Gebruik een accordion niet als alle content zichtbaar moet zijn om vragen van gebruikers te beantwoorden. De relevantie van de content is dan belangrijker dan de totale lengte van de pagina.

  ## Hoe te gebruiken
  Zorg dat de gebruiker meerdere delen tegelijk kan openen. De delen van een accordion hebben twee verschillende posities: ingeklapt en uitgeklapt. De posities zijn af te lezen aan de chevron. Wijst de chevron naar beneden, dan is de accordion ingeklapt. Wijst de chevron naar boven, dan is de accordion uitgeklapt. De accordion kan ook genest gebruikt worden.

  ## Gedrag en toegankelijkheid
  Let bij implementatie van het accordion op het volgende:
  * Gebruik voor de uitklapbare knoppen `<button>`.
  * Geef deze knoppen een heading op het juiste niveau.
      * Meestal is dat 1 niveau onder het niveau van de heading die boven het accordion staat. Stel dat het accordion direct onder de paginatitel staat (dat is een `<h1>`). Dan krijgt de knop `<h2>`.
      * In een genest accordion heeft de geneste knop een heading van 1 niveau onder de heading van de bovenliggende knop. Stel dat de bovenliggende knop een `<h2>` heeft. Dan krijgt de geneste knop een `<h3>`.
  * Geef de knoppen het aria-expanded attribuut. Screenreaders hebben dit attribuut nodig om te bepalen of een knop is ingeklapt of uitgeklapt.
  * Zorg dat je javascript het aria-expanded attribuut op "true" zet bij het uitklappen en op "false" bij het inklappen.
  * Zorg daarnaast dat je javascript de modifier .dso-open meegeeft (zie html) aan de bovenliggende div van een uitgeklapte knop. De javascript moet de modifier weer weghalen bij het inklappen. Daarmee zorg je dat het verschil tussen een ingeklapte knop en een uitgeklapte knop goed zichtbaar is.
  * Voegt u via een modifier een statusicoon toe aan de uitklapbare knop (.dso-succes, .dso-warning, .dso-info of .dso-danger)? Let dan op de volgende dingen:
    * Beschrijf de betekenis van het statusicoon in de context van de accordion met een .sr-only span. Plaats deze in de tekst van de knop.
    * Voorbeeldtekst voor .dso-succes: "Informatie bouwwerkzaamheden `<span class="sr-only">(afgerond)</span>`"

  ## Component in context
  - [Aanvragen]({{ '/components/detail/aanvragen' | docPath }})

  ## Bronvermelding
  - U.S. Web Design System (USWDS). Components Accordion. Geraadpleegd op 20 maart 2020, van https://designsystem.digital.gov/components/accordion/
  - NN/g Nielsen Norman Group. Accordions complex content. Geraadpleegd op 20 maart 2020, van https://www.nngroup.com/articles/accordions-complex-content
  - W3C. (2019, 14 augustus). WAI-ARIA Authoring Practices 1.1: 3.1 Accordion (Sections With Show/Hide Functionality)Geraadpleegd op 23 juli 2020, van https://www.w3.org/TR/wai-aria-practices/#accordion

status: ready
context:
  __title: default
  sections:
  - title: Oprit (h2)
    id: panel_oprit
    header: h2
  - title: Woning (h3)
    id: default_panel1
    open: true
    header: h3
    richContent: |
      <p>Dit is de inhoud van <strong>Woning (h2)</strong></p>
      <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
  - title: Bouwwerkzaamheden (h4)
    id: default_panel2
    state: success
    header: h4
  - title: Plaats van het bouwwerk (h5)
    id: default_panel3
    state: warning
    header: h5
    richContent: |
      <p>Dit is de inhoud van <strong>Plaats van het bouwwerk (h4)</strong></p>
      <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
    open: true
    sections:
    - title: Woning (h2)
      id: default_subpanel1
      header: h2
    - title: Bouwwerkzaamheden (h3)
      id: default_subpanel2
      open: true
      state: success
      header: h3
      richContent: |
        <p>Dit is een geneste accordion. De inhoud is van <strong>Bouwwerkzaamheden (h3)</strong>. Zie de <em>Notes</em> van dit component.</p>
    - title: Plaats van het bouwwerk (h4)
      id: default_subpanel3
      state: warning
      header: h4
    - title: Afmetingen van het bouwwerk (h5)
      id: default_subpanel4
      state: info
      header: h5
    - title: Extra werkzaamheden (h5)
      id: default_subpanel5
      state: danger
      header: h5
  - title: Afmetingen van het bouwwerk (h5)
    id: default_panel4
    state: info
    header: h5
  - title: Extra werkzaamheden (h5)
    id: default_panel5
    state: danger
    header: h5
    status: 5 van 8 beantwoord
  - title: Optionele werkzaamheden (h5)
    id: default_panel6
    state: warning
    header: h5
    richContent: |
      <p>Dit is de inhoud van <strong>Optionele werkzaamheden (h5)</strong></p>
      <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
    open: true
    status: 6 van 8 beantwoord
  - title: Bijgevoegde werkzaamheden (h5)
    id: default_panel7
    header: h5
    attachments: 2
  - title: Afsluitende werkzaamheden (h5)
    id: default_panel8
    header: h5
    status: 7 van 8 beantwoord
  - title: Evaluatie werkzaamheden (h5)
    id: default_panel9
    header: h5
    attachments: 1
    richContent: |
      <p>Dit is de inhoud van <strong>Evaluatie werkzaamheden (h5)</strong></p>
      <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
    open: true
variants:
  - name: default met links
    context:
      __title: default met links
      sections:
      - title: Oprit (h2)
        id: default-links_panel1
        type: link
        header: h2
      - title: Woning (h3)
        id: default-links_panel2
        type: link
        open: true
        header: h3
        richContent: |
          <p>Dit is de inhoud van <strong>Woning (h2)</strong></p>
          <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
      - title: Bouwwerkzaamheden (h4)
        id: default-links_panel3
        type: link
        state: success
        header: h4
      - title: Plaats van het bouwwerk (h5)
        id: default-links_panel4
        type: link
        state: warning
        header: h5
        richContent: |
          <p>Dit is de inhoud van <strong>Plaats van het bouwwerk (h4)</strong></p>
          <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
        open: true
        sections:
        - title: Woning (h2)
          id: default-links_subpanel1
          type: link
          header: h2
        - title: Bouwwerkzaamheden (h3)
          id: default-links_subpanel2
          type: link
          open: true
          state: success
          header: h3
          richContent: |
            <p>Dit is een geneste accordion. De inhoud is van <strong>Bouwwerkzaamheden (h3)</strong>. Zie de <em>Notes</em> van dit component.</p>
        - title: Plaats van het bouwwerk (h4)
          id: default-links_subpanel3
          type: link
          state: warning
          header: h4
        - title: Afmetingen van het bouwwerk (h5)
          id: default-links_subpanel4
          type: link
          state: info
          header: h5
        - title: Extra werkzaamheden (h5)
          id: default-links_subpanel5
          type: link
          state: danger
          header: h5
      - title: Afmetingen van het bouwwerk (h5)
        id: default-links_panel5
        type: link
        state: info
        header: h5
      - title: Extra werkzaamheden (h5)
        id: default-links_panel6
        type: link
        state: danger
        header: h5
        status: 5 van 8 beantwoord
      - title: Optionele werkzaamheden (h5)
        id: default-links_panel7
        type: link
        state: warning
        header: h5
        richContent: |
          <p>Dit is de inhoud van <strong>Optionele werkzaamheden (h5)</strong></p>
          <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
        open: true
        status: 6 van 8 beantwoord
      - title: Bijgevoegde werkzaamheden (h5)
        id: default-links_panel8
        type: link
        header: h5
        attachments: 2
      - title: Afsluitende werkzaamheden (h5)
        id: default-links_panel9
        type: link
        header: h5
        status: 7 van 8 beantwoord
      - title: Evaluatie werkzaamheden (h5)
        id: default-links_panel10
        type: link
        header: h5
        attachments: 1
        richContent: |
          <p>Dit is de inhoud van <strong>Evaluatie werkzaamheden (h5)</strong></p>
          <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
        open: true
  - name: default met formulier
    context:
      __title: default met formulier
      sections:
      - title: Stap met formulier zonder fieldset
        id: default-formulier_panel1
        open: true
        fieldsets:
          - groups:
              - id: omgevingsvergunningPostcode
                inputType: input
                type: text
                label: Postcode
                size: 8
              - id: brandstof
                label: Brandstof
                inputType: radios
                options:
                - value: 1
                  label: benzine
                - value: 2
                  label: diesel
              - id: schrijfwaar
                label: Schrijfwaar
                inputType: radios
                options:
                - value: 1
                  label: pen
                - value: 2
                  label: potlood
              - id: omgevingsvergunningHuisnummer
                inputType: input
                type: text
                label: Huisnummer
                size: 8
              - id: omgevingsvergunningToevoeging
                inputType: input
                type: text
                label: Huisnummer toevoeging
                size: 8
              - id: omgevingsvergunningStraatnaam
                inputType: input
                type: text
                label: Straatnaam
              - id: omgevingsvergunningWoonplaats
                inputType: input
                type: text
                label: Woonplaats
              - id: type_melder
                inputType: radios
                label: Type melder
                options:
                - value: particulier
                  label: particulier
                - value: bedrijf
                  label: bedrijf
        buttons:
        - type: submit
          modifier: primary
          label: Volgende stap
      - title: Stap met formulier met meerdere fieldsets
        id: default-formulier_panel2
        open: true
        header: h5
        fieldsets:
          - legend: Adresgegevens
            groups:
              - id: omgevingsvergunningPostcode
                inputType: input
                type: text
                label: Postcode
                size: 8
              - id: omgevingsvergunningHuisnummer
                inputType: input
                type: text
                label: Huisnummer
                size: 8
              - id: omgevingsvergunningToevoeging
                inputType: input
                type: text
                label: Huisnummer toevoeging
                size: 8
              - id: omgevingsvergunningStraatnaam
                inputType: input
                type: text
                label: Straatnaam
              - id: omgevingsvergunningWoonplaats
                inputType: input
                type: text
                label: Woonplaats
          - legend: Melder gegevens
            groups:
              - id: type_melder
                inputType: radios
                label: Type melder
                options:
                - value: particulier
                  label: particulier
                - value: bedrijf
                  label: bedrijf
        buttons:
        - type: button
          modifier: link
          label: Annuleren
        - type: submit
          modifier: primary
          label: Verstuur
  - name: default met definition-list
    context:
      __title: default met definition-list
      sections:
      - title: Stap met definition-list
        id: default-definition-list_panel1
        open: true
        definitions:
        - term: "Indienen bij:"
          descriptions:
            - description: Gemeente Den Haag
        - term: "Soort:"
          descriptions:
            - description: Melding
        - term: "Bevat:"
          descriptions:
            - description: Milieubelastende activiteit - Vergunning (Gemeente)
        - term: "Omgevingsoverleg mogelijk:"
          descriptions:
            - description: Ja
  - name: compact
    context:
      __title: compact
      modifiers: dso-accordion-compact
      sections:
        - title: Sectie titel (active)
          id: default-compact_panel1
          header: h3
          richContent: |
            <p>Dit is de inhoud van <strong>Sectie titel (active)</strong></p>
            <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
          open: true
        - title: Sectie titel
          id: default-compact_panel2
          header: h3
        - title: Sectie titel
          id: default-compact_panel3
          header: h3
        - title: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vehicula, ipsum eu porttitor cursus, metus ante ultricies quam, quis egestas urna justo a quam.
          id: default-compact_panel4
          header: h3
  - name: compact met links
    context:
      __title: compact met links
      modifiers: dso-accordion-compact
      sections:
        - title: Sectie titel (active)
          id: default-compact-links_panel1
          type: link
          header: h3
          richContent: |
            <p>Dit is de inhoud van <strong>Sectie titel (active)</strong></p>
            <p>Semantisch klopt deze pagina niet, maar om de styling voor de verschillende <code>.dso-accordion.handle</code>s te waarborgen staan alle varianten in het DOM (<code>h2</code>, <code>h3</code>, <code>h4</code>, <code>h5</code>)</p>
          open: true
        - title: Sectie titel
          id: default-compact-links_panel2
          type: link
          header: h3
        - title: Sectie titel
          id: default-compact-links_panel3
          type: link
          header: h3
        - title: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vehicula, ipsum eu porttitor cursus, metus ante ultricies quam, quis egestas urna justo a quam.
          id: default-compact-links_panel4
          type: link
          header: h3
