status: ready
collated: true
context:
  __title: Zichtbaar label met icoon
  placeholder: Placeholder
  icon: true
  label: Label
variants:
  - name: label-no-icon
    context:
      __title: Zichtbaar label, geen icon
      icon: false
  - name: huge-placeholder
    context:
      placeholder: Placeholder met lange tekst, lange tekst, langere tekst. Placeholder met lange tekst, lange tekst, langere tekst. Placeholder met lange tekst, lange tekst, langere tekst.
      __title: Lange tekst in placeholder
      icon: false
  - name: hidden-label-icon
    context:
      __title: Verborgen label met icon
      hiddenLabel: true
  - name: hidden-label-no-icon
    context:
      __title: verborgen label, geen icon
      hiddenLabel: true
      icon: false
  - name: with-value
    context:
      __title: Met waarde
      value: Waarde
      clearButton: true
  - name: invalid
    context:
      __title: Invalid
      modifier: dso-invalid
  - name: hidden-button
    context:
      __title: Verborgen knop
      hideSearchButton: true
  - name: with-results
    context:
      __title: Met resultaten-melding
      hideSearchButton: true
      value: Activiteit
      resultsMessage: 7 gevonden resultaten
  - name: with-hidden-results
    context:
      __title: Met verborgen resultaten-melding
      hideSearchButton: true
      value: Activiteit
      resultsMessage: 7 gevonden resultaten
      resultsHidden: true
