notes: |
order: 4
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: 7. Verzoeken indienen
    step: Stap 7 van 7
  form:
    formModifier: form-vertical
    fieldsets:
    - groups:
      - id: verzoek
        inputType: radios
        inline: true
        label: Wilt u uw verzoeken definitief of als Omgevingsoverleg indienen?
        options:
        - value: Omgevingsoverleg
          label: Omgevingsoverleg
        - value: definitiefverzoek
          label: Definitief verzoek
  highlightbox:
    yield: |
      <div class="dso-rich-content">
        <p>
          Als u wilt, kunt u een aanvraag doen voor een Omgevingsoverleg. Het Omgevingsoverleg is een zorgvuldig proces waarin u uw plan bespreekt met uw gemeente, waterschap of provincie en andere betrokkenen. Samen kijkt u dan naar hoe haalbaar uw plan is, en hoe u uw plan het beste mogelijk kunt maken. Bij elk verzoek staat aangegeven of het mogelijk is om een Omgevingsoverleg in te dienen.
        </p>
        <p>
          Twijfelt u over uw plan, of heeft u een vraag? Neem dan contact op met uw gemeente, waterschap of provincie.
        </p>
        <p>
          Let op: kijk altijd eerst op de website van <em>Gemeente Den Haag</em> voor de mogelijke kosten van een Omgevingsoverleg.
        </p>
      </div>
  definitionlist1:
    definitions:
    - term: "Verzoek 1:"
      descriptions:
        - description: Object Laan van Eik en Duinen 125, 's-Gravenhage 1
    - term: "Indienen bij:"
      descriptions:
        - description: Hoogheemraadschap van Delfland
    - term: "Soort:"
      descriptions:
        - description: Aanvraag vergunning
    - term: "Bevat:"
      descriptions:
        - description: Milieubelastende activiteit - Vergunning (Gemeente)
    - term: "Omgevingsoverleg mogelijk:"
      descriptions:
        - description: Nee
  definitionlist2:
    definitions:
    - term: "Verzoek 2:"
      descriptions:
        - description: Object Laan van Eik en Duinen 125, 's-Gravenhage 2
    - term: "Indienen bij:"
      descriptions:
        - description: Gemeente Den Haag
    - term: "Soort:"
      descriptions:
        - description: Melding
    - term: "Bevat:"
      descriptions:
        - description: Milieubelastende activiteit - Vergunning (Gemeente)
    - term: "Omgevingsoverleg mogelijk:"
      descriptions:
        - description: Ja
