status: wip
collated: true
context:
  id: input-text
  type: text
  label: Tekstveld
variants:
- name: input-text-invalid
  context:
    __title: Ongeldig
    __explanation:
    - Indien een input ongeldig is, dient er een <code>.dso-invalid</code> class
      gezet te worden op de div met de class <code>.dso-input</code>.
    id: input-text-invalid
    label: E-mailadres
    value: thomas@
    required: true
    helpText: 'Bijvoorbeeld: email@email.nl'
    state: invalid
    errorText: Ongeldig e-mailadres ingevuld
- name: input-text-valid
  context:
    __title: Geldig
    __explanation:
    - Indien een input ongeldig was en valide wordt gemaakt, dient de
      <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-text-valid
    label: E-mailadres
    value: thomas@infoprojects.nl
    required: true
    state: valid
    helpText: 'Bijvoorbeeld: email@email.nl'
- name: input-text-placeholder
  context:
    __title: Placeholder
    id: input-text-placeholder
    label: Naam
    placeholder: Voornaam Achternaam
    required: true
- name: input-text-icon
  context:
    __title: Met icoon
    id: input-text-icon
    label: E-mailadres
    inputIcon: fas fa-at
- name: input-text-disabled
  context:
    __title: Disabled
    id: input-text-disabled
    label: Naam
    disabled: true
- name: input-text-readonly
  context:
    __title: Readonly
    id: input-text-readonly
    label: Naam
    readonly: true
- name: input-text-infobutton
  context:
    __title: Infobutton
    __explanation:
    - Toelichting ingeklapt
    id: input-text-infobutton
    label: E-mailadres
    value: thomas@
    infoOpen: false
    infoText: |
      Closed
- name: input-text-infobutton-open
  context:
    __title: Infobutton uitgeklapt
    __explanation:
    - Toelichting uitgeklapt
    id: input-text-infobutton-open
    label: E-mailadres
    required: true
    infoOpen: true
    infoText: |
      <h4>Heading 4</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
