status: wip
collated: true
context:
  label: Kleur van object
  value: Rood
variants:
- name: static
  context:
    __title: Static
    __explanation:
    - Een static input kan informatie tonen die van belang is in een formulier zonder dat er een keuze gemaakt dient te worden.
- name: static-infobutton
  context:
    __title: Static infobutton
    infoButton: true
    infoButtonLabel: Toelichting
    infoOpen: false
- name: static-infobutton-open
  context:
    __title: Static infobutton uitgeklapt
    infoButton: true
    infoButtonLabel: Toelichting
    infoOpen: true
    infoTitle: Toelichting titel
    infoLink: Lees meer
    infoLinkIcon: fas fa-chevron-down
    infoText: |
      <h4>Heading 4</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>

