notes: |
  Een radio group heeft een root element `fieldset.form-group`, en geen `div.form-group`.
status: wip
collated: true
context:
  id: input-radio
  label: Maak een keuze
  helpText: Kies een oneven getal
  options:
  - value: 1
    label: een
  - value: 2
    label: twee
  - value: 3
    label: drie
variants:
- name: input-radio-required
  context:
    __title: Verplicht
    __explanation:
    - Een verplichte keuze wordt in de markup aangegeven met <code>.dso-required</code>
      op de <code>.form-group.dso-radios</code>
    - Radiobuttons hebben (net zoals checkboxen) een <code>fieldset.form-group</code> als
      root element, geen <code>div.form-group</code>
    id: input-radio-required
    required: true
- name: input-radio-invalid
  context:
    __title: Ongeldig
    __explanation:
    - Indien een radio groep ongeldig is, dient er een <code>.dso-invalid</code>
      class gezet te worden op de div met de class <code>.dso-radios</code>.
    id: input-radio-invalid
    required: true
    state: invalid
    errorText: Foutieve keuze
    options:
    - value: 1
      label: een
    - value: 2
      label: twee
      checked: true
    - value: 3
      label: drie
- name: input-radio-valid
  context:
    __title: Geldig
    __explanation:
    - Indien een radio groep ongeldig was en valide wordt gemaakt, dient de <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-radio-valid
    required: true
    state: valid
    options:
    - value: 1
      label: een
      checked: true
    - value: 2
      label: twee
    - value: 3
      label: drie
- name: input-radio-disabled
  context:
    __title: Disabled
    id: input-radio-disabled
    required: true
    state: valid
    options:
    - value: 1
      label: een
      disabled: true
    - value: 2
      label: twee
      disabled: true
    - value: 3
      label: drie
      checked: true
      disabled: true
- name: input-radio-inline
  context:
    __title: Inline
    __explanation:
    - Een keuze selectie tussen <code>ja</code> en <code>nee</code> vraagt om een inline variant. Dit is te bereiken door <code>.dso-inline</code> op <code>.dso-radios</code> te zetten.
    id: input-radio-inline
    label: Gaat het om de bouw van één of meer woningen?
    helpText: ""
    required: true
    inline: true
    options:
    - value: 1
      label: ja
      checked: true
    - value: 2
      label: nee
- name: input-radio-inline-info
  context:
    __title: Inline
    __explanation:
    - Een keuze selectie tussen <code>ja</code> en <code>nee</code> vraagt om een inline variant. Dit is te bereiken door <code>.dso-inline</code> op <code>.dso-radios</code> te zetten.
    id: input-radio-inline
    label: Gaat het om de bouw van één of meer woningen?
    helpText: ""
    infoButton: true
    # required: true
    inline: true
    options:
    - value: 1
      label: ja
      checked: true
    - value: 2
      label: nee
