status: ready
collated: true
context:
  __title: default
  labels:
  - label: Label (standaard)
  - label: Label (succes)
    status: success
  - label: Label (primair)
    status: primary
  - label: Label (info)
    status: info
  - label: Label (waarschuwing)
    status: warning
  - label: Label (gevaar)
    status: danger
  - label: Label (helder)
    status: bright
  - label: Label tekst 8
  - label: Label tekst 9
  - label: Label tekst 10
  - label: Label tekst 11
  - label: Label tekst 12
variants:
  - name: align right
    context:
      __title: Rechts uitlijnen
      modifiers: dso-align-right
  - name: wc
    context:
      __title: with Label Web Component
