notes: |
order: 40
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
        active: true

