notes: |
  De aside met de checklist schuift mee met het formulier, tot hij een punt bereikt waar hij niet verder MAG scrollen.
  We gebruiken hiervoor Bootstrap Affix, en deze heeft twee values - `data-offset-top` en `data-offset-bottom` - die bepalen waar het kantelpunt zit.
  Let op de uitlijning die te zien is in onderstaande instructie afbeelding.

  Zie ook
  * [Bootstrap Affix](https://getbootstrap.com/docs/3.3/javascript/#affix)
  * Positioneren van de affix, links in het menu onder het kopje "Documentation"
status: ready
context:
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Vergunningcheck
        url: '#'
      
  sections:
  - title: Woning
    id: panel1
  - title: Bouwwerkzaamheden
    id: panel2
  - title: Plaats van het bouwwerk
    id: panel3
    open: true
    formLegend: Aanvraagformulier
    fieldsets:
      - legend: Plaats van het bouwwerk
        groups:
          - id: omgevingsvergunningPostcode
            inputType: input
            type: text
            label: Postcode
            size: 8
          - id: omgevingsvergunningHuisnummer
            inputType: input
            type: text
            label: Huisnummer
            size: 8
          - id: omgevingsvergunningToevoeging
            inputType: input
            type: text
            label: Huisnummer toevoeging
            size: 8
          - id: omgevingsvergunningStraatnaam
            inputType: input
            type: text
            label: Straatnaam
          - id: omgevingsvergunningWoonplaats
            inputType: input
            type: text
            label: Woonplaats
    submitButton:
      type: submit
      modifier: primary
      label: Volgende stap
  - title: Afmetingen van het bouwwerk
    id: panel4
  - title: Extra werkzaamheden
    id: panel5
