status: ready
context:
  columns:
    - label: Service
      items:
        - Contact
        - Sitemap
        - Help
    - label: Over deze site
      items:
        - Copyright
        - Privacy
        - Cookies
        - Toegankelijkheid
    - label: Volg ons ook op
      items:
        - Twitter
        - LinkedIn
