notes: |
  Toevoeging van de class class `.dso-open` op de `.dso-navbar` opent het mobiele navigatiemenu. Dit dient scriptend te gebeuren.
status: ready
context:
  searchbarContext:
    open: true
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
      - label: Regels op de kaart
        active: true
      - label: Mijn Omgevingsloket
    collapsed: false
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Checken
        url: '#'
