notes: |
  Een accordion (`.dso-accordion`) bestaat uit secties (`.dso-accordion-section`). Een sectie heeft een handle (`.dso-section-handle`) en body (`.dso-section-body`).

  Een accordion section in de state "open" moet een `.dso-open` class op `.dso-accordion-section` krijgen. Dit zorgt het "chevron-up"-icoon. Ook als het `.dso-accordion-section` element niet in het DOM staat, moet een open accordion altijd `.dso-open` krijgen.

  Er zijn 4 modifiers: `.dso-succes`, `.dso-warning`, `.dso-info` en `.dso-danger` die op de `.dso-accordion-section` kunnen.

  Het is mogelijk om een accordion in een accordion te plaatsen. Er moet dan wel `.dso-nested-accordion` op de `.dso-accordion-section` worden gezet.

status: ready
context:
  sections:
  - title: Oprit (div)
    id: panel_oprit
  - title: Woning (h1)
    id: panel1
    open: true
    header: h1
  - title: Bouwwerkzaamheden (h2)
    id: panel2
    state: success
    header: h2
  - title: Plaats van het bouwwerk (h3)
    id: panel3
    state: warning
    header: h3
    open: true
    sections:
    - title: Woning (div)
      id: panel1
    - title: Bouwwerkzaamheden (h2)
      id: panel2
      open: true
      state: success
      header: h2
    - title: Plaats van het bouwwerk (h3)
      id: panel3
      state: warning
      header: h3
    - title: Afmetingen van het bouwwerk (h4)
      id: panel4
      state: info
      header: h4
    - title: Extra werkzaamheden (h5)
      id: panel5
      state: danger
      header: h5
  - title: Afmetingen van het bouwwerk (h4)
    id: panel4
    state: info
    header: h4
  - title: Extra werkzaamheden (h5)
    id: panel5
    state: danger
    header: h5
    countertext: 5 van 8 beantwoord
  - title: Optionele werkzaamheden (h5)
    id: panel6
    state: warning
    header: h5
    open: true
    countertext: 6 van 8 beantwoord
  - title: Bijgevoegde werkzaamheden (h5)
    id: panel7
    state: attachment
    header: h5
    countertext: 7 van 8 beantwoord
    attachment: true
  - title: Afsluitende werkzaamheden (h5)
    id: panel8
    header: h5
    countertext: 7 van 8 beantwoord
