notes: |
order: 40
status: ready
context:
  steps:
    title: H1 nog te bepalen
    subtitle: 3. Kies activiteiten
    step: Stap 3/7
  alert:
    status: info
    message: Hulp nodig bij kiezen? Doe dan eerst de <a href="#">Vergunningscheck</a>.
  shoppingcart:
    shoppingcartTitle: Mijn activiteiten
    shoppingcartTitleTag: h3
    items:
      - label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
        additive: 1
    collapsed: true
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    placeholder: Bijvoorbeeld bouwactiviteiten
    icon: true
    id: filter_activiteiten
    hideSearchButton: true
    clearButton: true
  formFacets:
  - legend: |
      <h4>Filters</h4>
    groups:
    - id: facets
      inputType: checkboxes
      label: Bestuurslaag
      options:
      - value: 1
        label: Rijk (18)
        id: checkbox_1
      - value: 2
        label: Gemeente (4)
        id: checkbox_2
    - id: facets
      inputType: checkboxes
      label: Toestemming
      options:
      - value: 1
        label: Aanvraag vergunning (11)
        id: checkbox_3
      - value: 2
        label: Aanvraag maatwerkvoorschrift (3)
        id: checkbox_4
      - value: 3
        label: Melding (7)
        id: checkbox_5
      - value: 4
        label: Informatie (1)
        id: checkbox_6
  listButtons:
  - type: button
    label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
    sublabel: 'Rijk'
    count: '1'
  - type: button
    label: Bouwen dakkapel - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: In stand houden van bouwwerken - Melding
    sublabel: Gemeente
  - type: button
    label: Milieubelastende activiteit - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: Opslaan van vloeistoffen in opslagtanks of in tankcontainers of verpakkingen gebruikt als opslagtank  - Aanvraag vergunning
    sublabel: Rijk
  asideButtons:
  - type: link
    modifier: link
    label: Vorige stap
    icon: chevron-left
  buttons:
  - type: submit
    modifier: primary
    label: Volgende stap
    iconAfter: chevron-right
