notes: |
order: 40
status: ready
context:
  appheading:
    title: Aanvraag Laan van Eik en Duinen 125, Den Haag
    subtitle: 3. Activiteiten
    step: Stap 3/7
  alert:
    status: info
    message: Hulp nodig bij kiezen? Doe dan eerst de <a href="#">Vergunningscheck</a>.
  shoppingcart:
    shoppingcartTitle: Mijn activiteiten
    shoppingcartTitleTag: h3
    items:
      - label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
        additive: 1
    collapsed: true
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    placeholder: Bijvoorbeeld bouwactiviteiten
    icon: true
    id: filter_activiteiten
    hideSearchButton: true
    clearButton: true
  formFacets:
  - legend: |
      <h4>Filters</h4>
    groups:
    - id: facets
      inputType: checkboxes
      label: Bestuurslaag
      options:
      - value: 1
        label: Rijk (18)
        id: checkbox_1
      - value: 2
        label: Gemeente (4)
        id: checkbox_2
    - id: facets
      inputType: checkboxes
      label: Toestemming
      options:
      - value: 1
        label: Aanvraag vergunning (11)
        id: checkbox_3
      - value: 2
        label: Aanvraag maatwerkvoorschrift (3)
        id: checkbox_4
      - value: 3
        label: Melding (7)
        id: checkbox_5
      - value: 4
        label: Informatie (1)
        id: checkbox_6
  typeSelect:
    id: sorting-select
    inputType: select
    label: 'Sorteer op:'
    options:
      - value: most-chosen
        label: Meest gekozen
      - value: alphabetic
        label: Alfabetisch
        selected: true
  labelGroup:
    labels:
    - label: Gemeente
      removable: true
    - label: Waterschap
      removable: true
    - label: Provincie
      removable: true
    - label: Rijksoverheid
      removable: true
    - label: Aanvraag vergunning
      removable: true
    - label: Melding
      removable: true
    - label: Informatie
      removable: true
    - label: Informatie ongewoon voorval
      removable: true
    - label: Aanvraag maatwerkvoorschrift
      removable: true
    - label: Melding gelijkwaardige maatregel
      removable: true
    - label: Aanvraag toestemming gelijkwaardige maatregel
      removable: true
  listButtons:
  - type: button
    label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
    sublabel: 'Rijk'
    count: '1'
  - type: button
    label: Bouwen dakkapel - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: In stand houden van bouwwerken - Melding
    sublabel: Gemeente
    count: 0
    inputNumber: true
    id: in-stand-houden-van-bouwwerken
    minusButtonLabel: Aantal verlagen
    plusButtonLabel: Aantal verhogen
  - type: button
    label: Milieubelastende activiteit - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: Opslaan van vloeistoffen in opslagtanks of in tankcontainers of verpakkingen gebruikt als opslagtank  - Aanvraag vergunning
    sublabel: Rijk
  asideButtons:
  - type: link
    modifier: dso-tertiary
    label: Vorige stap
    icon: chevron-left
  buttons:
  - type: submit
    modifier: dso-primary
    label: Volgende stap
    iconAfter: chevron-right
