notes: |
order: 90
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: Object Laan van Eik en Duinen 125, Den Haag
    subtitle: 7. Verzoeken indienen
    step: Stap 7 van 7
  accordion:
    modifiers: form-horizontal
    sections:
    - title: "Verzoek 1: Object Laan van Eik en Duinen 125, 's-Gravenhage 1"
      id: panel1
      open: true
      definitions:
      - term: "Indienen bij:"
        descriptions:
          - description: Gemeente Den Haag
      - term: "Soort:"
        descriptions:
          - description: Aanvraag vergunning
      - term: "Bevat:"
        descriptions:
          - description: Milieubelastende activiteit - Vergunning (Gemeente)
      - term: "Doel:"
        descriptions:
          - description: Definitief verzoek
      fieldsets:
        - legend: Verzoek
          groups:
          - id: toelichting
            inputType: textarea
            rows: 5
            label: Ruimte om uw verzoek toe te lichten
        - groups:
            - id: documenten1
              label: Vraag om bijlage
              inputType: files
              infoOpen: false
              infoButtonLabel: Toelichting bij Vraag om bijlage
              infoText: none
              files:
                - filename: Bestand.pdf
        - legend: Vragengroep titel
          groups:
          - id: classificatie
            inputType: input
            label: Vraag met classificatie 'verzoek'
      buttons:
      - type: button
        modifier: primary
        label: Volgende
    - title: "Verzoek 2: Object Laan van Eik en Duinen 125, 's-Gravenhage 2"
      id: panel2
  form:
    fieldsets:
    - modifier: form-vertical
      groups:
      - id: confirm
        inputType: confirm
        label: Hierbij verklaar ik alle vragen naar waarheid te hebben ingevuld.
    asideButtons:
    - type: button
      modifier: link
      label: Vorige
      icon: chevron-left
    buttons:
    - type: button
      modifier: link
      label: Downloaden
      icon: download
    - type: submit
      modifier: primary
      label: Indienen
