notes: |
order: 70
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: Object Laan van Eik en Duinen 125, Den Haag
    subtitle: 7. Verzoeken indienen
    step: Stap 7 van 7
  alerts:
  - status: warning
    sronly: "Waarschuwing:"
    message: |
      Verander de instantie alleen als u zeker weet dat die niet klopt. Als u iets verandert, duurt het afhandelen van uw aanvraag mogelijk langer.
  - status: info
    sronly: "Opmerking:"
    message: |
      We hebben van uw aanvraag meerdere verzoeken gemaakt. Hier ziet u waar u de verzoeken indient.
  form:
    formModifier: form-horizontal
    fieldsets:
    - legend: Verzoek 1
      groups:
      - inputType: input
        type: text
        label: "Verzoek 1:"
        value: Object Laan van Eik en Duinen 125, 's-Gravenhage 1
      - inputType: select
        label: "Indienen bij:"
        options:
          - value: delfland
            label: Hoogheemraadschap van Delfland
          - value: denhaag
            label: Gemeente Den Haag
      - inputType: static
        label: "Soort:"
        value: Aanvraag vergunning
      - inputType: static
        label: "Bevat:"
        value: Milieubelastende activiteit - Vergunning (Gemeente)
    - legend: Verzoek 2
      groups:
      - inputType: static
        label: "Verzoek 2:"
        value: Object Laan van Eik en Duinen 125, 's-Gravenhage 1
        edit: true
      - inputType: select
        label: "Indienen bij:"
        options:
          - value: denhaag
            label: Gemeente Den Haag
          - value: delfland
            label: Hoogheemraadschap van Delfland
      - inputType: static
        label: "Soort:"
        value: Melding
      - inputType: static
        label: "Bevat:"
        value: Milieubelastende activiteit - Vergunning (Gemeente)
