default: Open
context:
  open: true
  toggleButton: true
  items:
    - label: Tankstation starten of veranderen
      activities:
        - label: Tanken van diesel, benzine en andere vloeibare brandstof
        - label: Tanken en opslaan van LPG
    - label: Opslaan van vloeistoffen in een opslagtank
      activities:
        - label: Opslaan van vloeistoffen in een ondergrondse opslagtank
          warning: true
variants:
  - name: empty
    context:
      items: []
  - name: closed
    context:
      open: false
  - name: no-toggle
    context:
      toggleButton: false
  - name: edit-name
    context:
      items:
        - label: Milieubeslastende activiteit - Melding
          edit: Naam bewerken
          activities: []
