notes: |
  Een definition list is een lijst met termen en een omschrijving of definitie daarvan. Gebruik de definition list bijvoorbeeld voor items die een directe relatie hebben met elkaar.

  ## Wanneer te gebruiken
  Gebruik de definition list om informatie samen te vatten. Denk bijvoorbeeld aan de antwoorden van een gebruiker aan het einde van een formulier.

  ## Hoe te gebruiken
  Bij een definition list staat de term links en de definitie rechts of op de volgende regel. Deze tekst is meestal ingesprongen in verhouding tot de term. De lijst moet een visueel ontwerp hebben en een layout die het belang van de content weergeeft en behoudt.

  Als gebruikers een lijst bekijken, willen ze snel kunnen zien welke van de items voor hen belangrijk zijn. Te veel informatie kan de gebruiker overladen en maakt de lijst onduidelijk. Te weinig informatie zorgt er juist weer voor dat de gebruiker het niet goed genoeg begrijpt. De hoeveelheid detail in de definitie moet daarom precies genoeg zijn.

  ## Gedrag en toegankelijkheid
  * Plaats een dubbele punt na de term. Dit geeft aan waar de term ophoudt en de definitie begint. Dit geeft gebruikers die met een sterke vergroting werken extra houvast. Een sterke vergroting zorgt er soms namelijk voor dat items op meerdere regels vallen, of dat het overzicht van het scherm wegvalt. Het is ook belangrijk voor gebruikers met cognitieve beperkingen en gebruikers van screenreaders die dit verschil niet duidelijk aangeven.

  ## Component in context
  - [Beheer-basis]({{ '/components/detail/beheer-basis' | docPath }})

  ## Bronvermelding
  - NN/g Nielsen Norman Group. The Anatomy of a List Entry. Geraadpleegd op 20 maart 2020, van https://www.nngroup.com/articles/list-entries/
  - Mozilla.org. MDN Web docs Mozilla. The Description List element. Geraadpleegd op 20 maart 2020, van https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
collated: true
context:
  __title: Standaard
  __explanation: Responsive component. Gedrag kan gestuurd worden met <code>.dso-vertical</code> en <code>.dso-emphasize-description</code>
  definitions:
    - term: "Thema"
      descriptions:
        - description: Wonen
        - description: Werken
    - term: "Regelkwalificatie"
      descriptions:
        - description: Instructieregels
    - term: "Onderwerp"
      descriptions:
        - description: Bedrijventerrein
    - term: "Functie"
      descriptions:
        - description:
            "Bedrijventerrein &gt; Bedrijventerrein"
    - term: "Type regel"
      descriptions:
        - description: Bindend voor bestuursorganen
    - term: "Normadressaat"
      longread:
        - paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        - paragraph: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - term: "Pneumonoultramicroscopicsilicovolcanoconiosisfantasismus"
      longread:
        - paragraph: Een factitious (quasi-fictieve) vorm van pneumoconiose (stoflongen), veroorzaakt door het inademen van microscopisch kleine silicadeeltjes uit vulkanen.
    - term: "De stoflongziekte (mijnwerkers-pneumoconiose)"
      longread:
        - paragraph: Veroorzaakt door lange blootstelling aan kolengruis.
    - term: "Pneumoconiose"
      longread:
        - paragraph: Pneumoconiose of stoflong is een longaandoening die door de inhalatie van stof wordt veroorzaakt.
variants:
  - name: accessibility
    context:
      __title: Gedrag en accessibility
      __explanation: Bij het gebruik van de definition list gebruik dan altijd een dubbele punt <code>:</code> achter de termen. Dit helpt gebruikers van screenreaders termen en definities makkelijker te relateren aan elkaar. Zie voorbeelden voor de implementatie.
  - name: vertical
    context:
      __title: Geforceerd verticale modus
      __explanation: Als het definitie component in smalle elementen wordt gebruikt kan de verticale modus worden gefoceerd met <code>.dso-vertical</code>
      modifier: dso-vertical
  - name: emphasize-description
    context:
      __title: Nadruk op beschrijving
      __explanation: Nadruk op de beschrijving door de termen niet dikgedrukt te maken en lichtere kleur te geven
      modifier: dso-emphasize-description
  - name: vertical-emphasize-description
    context:
      __title: Verticale modus met nadruk op beschrijving
      __explanation: null
      modifier: dso-vertical dso-emphasize-description
  - name: columns-1-3
    context:
      __title: Kolomverdeling 1-3
      __explanation: Kolomverdeling 1-3, groene koppen door class <code>dso-with-header</code>.
      modifier: dso-columns-1-3 dso-with-header
      definitions:
        - term: "Verzoek 1"
          descriptions:
            - description: Aanleg rondweg Leiden traject Rijnland route 1
        - term: "Verzoeknummer"
          descriptions:
            - description: 20181024 00729 000
        - term: "Datum ingediend"
          descriptions:
            - description: 24/10/2018
        - term: "Ingediend bij"
          descriptions:
            - description: Gemeente Den Haag
        - term: "Uw verzoek wordt behandeld door"
          descriptions:
            - description: Omgevingsdienst Haaglanden
  - name: columns-2-2
    context:
      __title: Kolomverdeling 2-2
      __explanation: Kolomverdeling 2-2 en <code>dso-with-header</code>.
      modifier: dso-columns-2-2 dso-with-header
      definitions:
        - term: "Verzoek 1"
          descriptions:
            - description: Aanleg rondweg Leiden traject Rijnland route 1
        - term: "Verzoeknummer"
          descriptions:
            - description: 20181024 00729 000
        - term: "Datum ingediend"
          descriptions:
            - description: 24/10/2018
        - term: "Ingediend bij"
          descriptions:
            - description: Gemeente Den Haag
        - term: "Uw verzoek wordt behandeld door"
          descriptions:
            - description: Omgevingsdienst Haaglanden
  - name: columns-3-1
    context:
      __title: Kolomverdeling 3-1
      __explanation: Kolomverdeling 3-1.
      modifier: dso-columns-3-1
      definitions:
        - term: "Verzoeknummer"
          descriptions:
            - description: 20181024 00729 000
        - term: "Datum ingediend"
          descriptions:
            - description: 24/10/2018
        - term: "Ingediend bij"
          descriptions:
            - description: Gemeente Den Haag
        - term: "Uw verzoek wordt behandeld door"
          descriptions:
            - description: Omgevingsdienst Haaglanden
  - name: two-columns-small-content
    context:
      __title: Twee kolommen
      __explanation: De combinatie van de classes <code>dso-columns</code> en <code>dso-2-columns</code> zorgt voor een verdeling van de inhoud over twee kolommen. Om ongewenste afbreek-problemen te voorkomen, dienen de <code>dl</code> en bijbehorende <code>dd</code>'s gegroepeerd te worden binnen een <code>div</code>.
      modifier: dso-columns dso-2-columns
      dsoColumns: true
      definitions:
        - term: "Organisator"
          descriptions:
            - description: Gemeente Rotterdam
        - term: "Verzoeknummer"
          descriptions:
            - description: 12123497987
        - term: "Status"
          descriptions:
            - description: Open
        - term: "Creatie datum"
          descriptions:
            - description: 17-12-2019
        - term: "Contactpersoon"
          descriptions:
            - description: Jan van Veen
        - term: "Emailadres"
          descriptions:
            - description: j.veen@testmail.nl
        - term: "Telefoonnummer"
          descriptions:
            - description: 06-12345678
  - name: two-columns
    context:
      __title: Twee kolommen, voorbeeld uitgebreide content
      __explanation: De combinatie van de classes <code>dso-columns</code> en <code>dso-2-columns</code> zorgt voor een verdeling van de inhoud over twee kolommen. Om ongewenste afbreek-problemen te voorkomen, dienen de <code>dl</code> en bijbehorende <code>dd</code>'s gegroepeerd te worden binnen een <code>div</code>.
      modifier: dso-columns dso-2-columns
      dsoColumns: true
  - name: three-columns-small-content
    context:
      __title: Drie kolommen
      __explanation: De combinatie van de classes <code>dso-columns</code> en <code>dso-3-columns</code> zorgt voor een verdeling van de inhoud over twee kolommen. Om ongewenste afbreek-problemen te voorkomen, dienen de <code>dl</code> en bijbehorende <code>dd</code>'s gegroepeerd te worden binnen een <code>div</code>.
      modifier: dso-columns dso-3-columns
      dsoColumns: true
      definitions:
        - term: "Organisator"
          descriptions:
            - description: Gemeente Rotterdam
        - term: "Verzoeknummer"
          descriptions:
            - description: 12123497987
        - term: "Status"
          descriptions:
            - description: Open
        - term: "Creatie datum"
          descriptions:
            - description: 17-12-2019
        - term: "Contactpersoon"
          descriptions:
            - description: Jan van Veen
        - term: "Emailadres"
          descriptions:
            - description: j.veen@testmail.nl
        - term: "Telefoonnummer"
          descriptions:
            - description: 06-12345678
  - name: three-columns
    context:
      __title: Drie kolommen, voorbeeld uitgebreide content
      __explanation: De combinatie van de classes <code>dso-columns</code> en <code>dso-3-columns</code> zorgt voor een verdeling van de inhoud over twee kolommen. Om ongewenste afbreek-problemen te voorkomen, dienen de <code>dl</code> en bijbehorende <code>dd</code>'s gegroepeerd te worden binnen een <code>div</code>.
      modifier: dso-columns dso-3-columns
      dsoColumns: true
  - name: bordered
    context:
      __title: Variant van definition list met borders
      __explanation: De class <code>dso-bordered,</code> zorgt op de definition list voor horizontale borders. De breedte classes <code>dso-columns-1-3</code>, <code>dso-columns-2-2,</code> en <code>dso-columns-3-1,</code> kunnen ook toegepast worden.
      modifier: dso-bordered
      definitions:
        - term: "Thema:"
          descriptions:
            - description: Wonen
            - description: Werken
        - term: "Regelkwalificatie:"
          descriptions:
            - description: Instructieregels
        - term: "Onderwerp:"
          descriptions:
            - description: Bedrijventerrein
        - term: "Functie:"
          descriptions:
            - description:
                "Bedrijventerrein &gt; Bedrijventerrein"
        - term: "Type regel:"
          descriptions:
            - description: Bindend voor bestuursorganen
        - term: "Normadressaat:"
          longread:
            - paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            - paragraph: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        - term: "Pneumonoultramicroscopicsilicovolcanoconiosisfantasismus:"
          longread:
            - paragraph: Een factitious (quasi-fictieve) vorm van pneumoconiose (stoflongen), veroorzaakt door het inademen van microscopisch kleine silicadeeltjes uit vulkanen.
        - term: "De stoflongziekte (mijnwerkers-pneumoconiose):"
          longread:
            - paragraph: Veroorzaakt door lange blootstelling aan kolengruis.
        - term: "Pneumoconiose:"
          longread:
            - paragraph: Pneumoconiose of stoflong is een longaandoening die door de inhalatie van stof wordt veroorzaakt.
  - name: with-list-in-columns
    context:
      __title: Met lijst in kolommen
      __explanation: Responsive component. Kolommen worden gezet doormiddel van <code>ul.dso-columns-list</code>.
      definitions:
        - term: "Trefwoorden"
          descriptions:
            - columnsList: |
                <ul class="dso-columns-list">
                  <li>aanbouwen</li>
                  <li>afvalcontainer</li>
                  <li>avegaarpaal</li>
                  <li>berging</li>
                  <li>bijbehorend bouwwerk</li>
                  <li>bijkeuken</li>
                  <li>blokhut</li>
                  <li>boorpaal</li>
                  <li>buispaal</li>
                  <li>buitenkeuken</li>
                  <li>carport</li>
                  <li>dierenverblijf</li>
                  <li>erker</li>
                  <li>fietsenberging</li>
                  <li>fietsenhok</li>
                  <li>fundering</li>
                  <li>garage</li>
                </ul>
