collated: true
context:
  __title: Radiobutton - Default
  type: radio
  label: Selecteer mij
variants:
  - name: radio-info-closed
    context:
      __title: Radiobutton - Info Closed
      id: radio-info-closed
      label: Selecteer mij
      infoText: |
        <p>Deze informatie is pas zichtbaar als de informatie-button wordt geactiveerd</p>
  - name: radio-info
    context:
      __title: Radiobutton - Info Open
      id: radio-info-open
      label: Selecteer mij
      infoOpen: true
      infoText: |
        <p>Toelichting bij optie</p>
  - name: radio-info-closed
    context:
      __title: Radiobutton - Info Static
      id: radio-info-static
      label: Selecteer mij
      infoStatic: true
      infoText: |
        <p>Deze toelichting kan niet worden gesloten</p>
  - name: checkbox
    context:
      __title: Checkbox - Default
      id: checkbox-default
      label: Selecteer mij
      type: checkbox
  - name: checkbox-info-closed
    context:
      __title: Checkbox - Info Closed
      id: checkbox-info-closed
      type: checkbox
      label: Selecteer mij
      infoText: |
        <p>Deze informatie is pas zichtbaar als de informatie-button wordt geactiveerd</p>
  - name: checkbox-info
    context:
      __title: Checkbox - Info Open
      id: checkbox-info-open
      type: checkbox
      label: Selecteer mij
      infoOpen: true
      infoText: |
        <p>Toelichting bij optie</p>
  - name: checkbox-info-closed
    context:
      __title: Checkbox - Info Static
      id: checkbox-info-static
      type: checkbox
      label: Selecteer mij
      infoStatic: true
      infoText: |
        <p>Deze toelichting kan niet worden gesloten</p>
  - name: checkbox-nested
    context:
      __title: Checkbox - Nested
      id: checkbox-nested
      type: checkbox
      label: Optie op hoofdniveau
      nestedOptions:
      - value: 1.1
        type: checkbox
        label: Optie op niveau 1 - keuze 1
        id: checkbox-sub-1-1
        name: checkbox-sub-1
        checked: true
        infoOpen: true
        infoText: |
          <h4>Toelichting bij antwoord: "Optie op niveau 1 - keuze 1"</h4>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
          </p>
        nestedOptions:
        - value: 1.1.1
          type: checkbox
          label: Optie op niveau 1.1 - keuze 1
          id: checkbox-sub-1-1-1
          name: checkbox-sub-1-1
        - value: 1.1.2
          type: checkbox
          label: Optie op niveau 1.1 - keuze 2
          id: checkbox-sub-1-1-2
          name: checkbox-sub-1-1
      - value: 1.2
        type: checkbox
        label: Optie op niveau 1 - keuze 2
        id: checkbox-sub-1-2
        name: checkbox-sub-1
        nestedOptions:
        - value: 1.2.1
          type: checkbox
          label: Optie op niveau 1.2 - keuze 1
          id: checkbox-sub-1-2-1
          name: checkbox-sub-1-2
        - value: 1.2.2
          type: checkbox
          label: Optie op niveau 1.2 - keuze 2
          id: checkbox-sub-1-2-2
          name: checkbox-sub-1-2
      - value: 1.3
        type: checkbox
        label: Optie op niveau 1 - keuze 3
        id: checkbox-sub-1-3
        name: checkbox-sub-1
        nestedOptions:
        - value: 1.3.1
          type: radio
          label: Optie op niveau 1.3 - keuze 1
          id: radio-sub-1-3
          name: radio-sub-1-3
        - value: 1.3.2
          type: radio
          label: Optie op niveau 1.3 - keuze 2
          id: radio-sub-1-3
          name: radio-sub-1-3
      - value: 1.4
        type: checkbox
        label: Optie op niveau 1 - keuze 4
        id: checkbox-sub-1-4
        name: checkbox-sub-1

