meta:
  webComponent: dso-highlight-box
status: ready
notes: Standaard achtergrondkleur grijs, andere varianten geel (modifier <code>dso-yellow</code>) en met grijze border (modifier <code>dso-border</code>).
context:
  __title: Standaard
  yield: |
    <div class="dso-rich-content">
      <h3>Toelichting: Vergunningvrij onder voorbehoud</h3>
      <p>Het Informatiehuis Bouw kent, op basis van de huidige gebruikerswensen, vier Informatieproducten, namelijk het Opleverdossier, de Bouwregelgeving, de Vergunningvrije bouwwerken en een Digitaliseringshulp.</p>
      <p>Het Opleverdossier (zie voor een nadere omschrijving van de informatieproducten de volgende paragrafen) is de, door gebruikers gewenste, centrale registratie waarin alle informatie over een bouwwerk is opgenomen. Het gaat hierbij om de tekeningen, berekeningen en de resultaten van de kwaliteitsborging (zoals toetsen en inspecties).</p>
      <p>De <a href="#">Bouwregelgeving</a> is een database met alle bouwregelgeving in Nederland, die op zodanige wijze moet zijn ingericht en ontsloten dat die voldoet aan de eisen van de Omgevingswet (3B's), en daarmee bruikbaar is in de ontwerp- en toetsingsfase van ieder bouwwerk.</p>
      <p>Het derde informatieproduct zijn de Vergunningvrije bouwwerken, hierin zijn opgenomen de (bekende) bouwwerken die vergunningvrij, maar niet regelvrij, zijn gerealiseerd. Het vierde en vooralsnog laatste informatieproduct is de Digitaliseringshulp, een service voor het centraal en gestandaardiseerd digitaliseren van documenten.</p>
      <div class="dso-button-row">
        <a href="#" class="dso-primary">Primaire button</a>
        <a href="#" class="dso-secondary">Secundaire button</a>
        <a href="#" class="dso-tertiary btn-align">
          Tertiaire button
          <dso-icon icon="chevron-down"></dso-icon>
        </a>
      </div>
    </div>
variants:
  - name: yellow
    context:
      __title: Geel
      yellow: true
  - name: bordered
    context:
      __title: Met rand
      border: true
  - name: white-drop-shadow
    context:
      __title: Wit met schaduw
      white: true
      dropShadow: true
  - name: Step indicator
    context:
      __title: Met step indicator
      yellow: true
      step: 2
  - name: Icon indicator
    context:
      __title: Met icoon
      yellow: true
      icon: plus
      label: Plus
