status: ready
id: toggle-info-open
context:
  __title: default
  infoText: |
    <h2>Heading 2</h2>
    <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
    Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. <a href="#">Nullam</a> lacinia non ipsum sit amet varius.
    Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.</p>
    <a href="#" class="dso-primary">Primaire button</a>
    <a href="#" class="dso-secondary">Secundaire button</a>
    <a href="#" class="dso-tertiary btn-align">
      Tertiaire button
      <dso-icon icon="chevron-down"></dso-icon>
    </a>
variants:
- name: static-info
  context:
    __title: Vaste toelichting
    static: true
    infoText: |
      <h2>Heading 2</h2>
      <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
      Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. <a href="#">Nullam</a> lacinia non ipsum sit amet varius.
      Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.</p>
      <a href="#" class="dso-primary">Primaire button</a>
      <a href="#" class="dso-secondary">Secundaire button</a>
      <a href="#" class="dso-tertiary btn-align">
        Tertiaire button
        <dso-icon icon="chevron-down"></dso-icon>
      </a>
