status: ready
collated: true
context:
  button-label: Actie
  modifier: btn-default
  dropdown-label: Toggle Dropdown
  items:
    -
      - Actie
      - Andere actie
      - Nog iets anders hier
    -
      - Gescheiden link
variants:
  - name: buttonGroupLarge
    context:
      sizing: btn-group-lg
  - name: buttonGroupSmall
    context:
      sizing: btn-group-sm
  - name: buttonGroupExtraSmall
    context:
      sizing: btn-group-xs
