status: wip
collated: true
context:
  __title: Standaard
  __explanation: Responsive component. Gedrag kan gestuurd worden met <code>.dso-vertical</code> en <code>.dso-emphasize-description</code>
  definitions:
    - term: Thema
      descriptions:
        - description: Wonen
        - description: Werken
    - term: Regelkwalificatie
      descriptions:
        - description: Instructieregels
    - term: Onderwerp
      descriptions:
        - description: Bedrijventerrein
    - term: Functie
      descriptions:
        - description: Bedrijventerrein > Bedrijventerrein
    - term: Type regel
      descriptions:
        - description: Bindend voor bestuursorganen
    - term: Normadressaat
      longread:
        - paragraph: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        - paragraph: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - term: Pneumonoultramicroscopicsilicovolcanoconiosis
      longread:
        - paragraph: Een factitious (quasi-fictieve) vorm van pneumoconiose (stoflongen), veroorzaakt door het inademen van microscopisch kleine silicadeeltjes uit vulkanen.
variants:
  - name: vertical
    context:
      __title: Geforceerd verticale modus
      __explanation: Als het definitie component in smalle elementen wordt gebruikt kan de verticale modus worden gefoceerd met <code>.dso-vertical</code>
      modifier: dso-vertical
  - name: emphasize-description
    context:
      __title: Nadruk op beschrijving
      __explanation: Nadruk op de beschrijving door de termen niet dikgedrukt te maken en lichtere kleur te geven
      modifier: dso-emphasize-description
  - name: vertical-emphasize-description
    context:
      __title: null
      __explanation: null
      modifier: dso-vertical dso-emphasize-description
  - name: columns-1-3
    context:
      __title: Kolomverdeling 1-3
      __explanation: Kolomverdeling 1-3, groene koppen door class <code>dso-first-line-headers</code>.
      modifier: dso-columns-1-3 dso-first-line-headers
      definitions:
        - term: Verzoek 1
          descriptions:
            - description: Aanleg rondweg Leiden traject Rijnland route 1
        - term: Verzoeknummer
          descriptions:
            - description: 20181024 00729 000
        - term: Datum ingediend
          descriptions:
            - description: 24/10/2018
        - term: Ingediend bij
          descriptions:
            - description: Gemeente Den Haag
        - term: Uw verzoek wordt behandeld door
          descriptions:
            - description: Omgevingsdienst Haaglanden
  - name: columns-2-2
    context:
      __title: Kolomverdeling 2-2
      __explanation: Kolomverdeling 2-2, handmatige highlights met tag <code>strong</code> en class <code>dso-definition-highlight</code>.
      modifier: dso-columns-2-2 dso-emphasize-description
      definitions:
        - term: Verzoek 1
          emphasizeElement: true
          hightlightElement: dso-definition-highlight
          descriptions:
            - description: Aanleg rondweg Leiden traject Rijnland route 1
              emphasizeElement: true
              hightlightElement: dso-definition-highlight
        - term: Verzoeknummer
          descriptions:
            - description: 20181024 00729 000
        - term: Datum ingediend
          descriptions:
            - description: 24/10/2018
        - term: Ingediend bij
          descriptions:
            - description: Gemeente Den Haag
        - term: Uw verzoek wordt behandeld door
          descriptions:
            - description: Omgevingsdienst Haaglanden
  - name: columns-3-1
    context:
      __title: Kolomverdeling 3-1 met borders
      __explanation: Kolomverdeling 3-1, class <code>dso-dl-borders</code> geeft een lijn boven en onder.
      modifier: dso-columns-3-1 dso-emphasize-description dso-dl-borders
      definitions:
        - term: Verzoek 1
          descriptions:
            - description: Aanleg rondweg Leiden traject Rijnland route 1
        - term: Verzoeknummer
          descriptions:
            - description: 20181024 00729 000
        - term: Datum ingediend
          descriptions:
            - description: 24/10/2018
        - term: Ingediend bij
          descriptions:
            - description: Gemeente Den Haag
        - term: Uw verzoek wordt behandeld door
          descriptions:
            - description: Omgevingsdienst Haaglanden
