status: ready
collated: true
default: decorative
variants:
  - name: decorative
    context:
      icon: fa fa-road
  - name: semantic
    context:
      icon: fa fa-road
      title: Route via de snelweg
  - name: enlarged
    notes: Een font kan worden vergroot met modifier classes `.fa-2x` tot `.fa-6x`.
    context:
      icon: fa fa-question fa-2x
