notes: |
  Plaatst een lichtgewicht, flexibel component dat optioneel de gehele breedte van de viewport kan bevatten om belangrijke content van je site te tonen. Gebaseerd op Bootstrap Jumbotron.
status: ready
collated: true
context:
  __title: Jumbotron
  title: Aan de slag met de Omgevingswet
  content: Data en services van het digitaal stelsel Omgevingswet zijn in ontwikkeling en worden gedurende het project via het Ontwikkelaarsportaal ter beschikking gesteld voor derden. De datasets op dit platform zijn benaderbaar vie RESTfull APIs. In onze API store zijn de volgende services in beta versie beschikbaar.
variants:
  - name: button
    context:
      _rowModifier: full-width
      __title: Jumbotron met Button
      button:
        label: Aan de slag
        type: button
        modifier: link
        state: standard
        icon: angle-right
  - name: image
    context:
      __title: Jumbotron met Image
      image:
        source: /dummy/images/avatar.png
        alt: Alternatieve tekst
  - name: image-button
    context:
      __title: Jumbotron met Button en Image
      image:
        source: /dummy/images/avatar.png
        alt: Alternatieve tekst
      button:
        label: Aan de slag
        type: button
        modifier: link
        state: standard
        icon: angle-right
