notes: |
  Het `.dso-card` component mag alleen in `.dso-card-list` of `.dso-card-grid` worden gebruikt.
collated: true
variants:
- name: default
  context:
    label: Omgevingsplan Nieuwegein
    content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing
      elit.
- name: interactions
  context:
    label: Brouwersmolen
    content: Brouwersmolen eget iaculis nisi quam in libero.
    interactions:
    - button:
        type: button
        modifier: dso-tertiary
        icon: info
        label: Toon informatie over Brouwersmolen
        iconOnly: true
