notes: |
  Het `dso-card` component mag alleen in het `dso-card-list` worden gebruikt.
collated: true
variants:
- name: default
  context:
    label: Omgevingsplan Nieuwegein
    content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing
      elit.
- name: aside
  context:
    label: Brouwersmolen
    content: Brouwersmolen eget iaculis nisi quam in libero.
    interactions:
    - button:
        type: button
        modifier: dso-tertiary
        icon: info
        label: Toon informatie over Brouwersmolen
        iconOnly: true
- name: below
  context:
    label: Brouwersmolen
    content: Brouwersmolen eget iaculis nisi quam in libero.
    interactions:
    - button:
        type: button
        modifier: dso-tertiary
        icon: info
        label: Toon informatie over Brouwersmolen
        iconOnly: true
