status: ready
collated: true
notes: Openen van het hamburger menu gaat door `.dso-open` naast `.dso-nav-bar` te zetten
context:
  __title: 'Example: open/close'
  __explanation: Verklein de viewport en gebruik de checkbox om het responsive gedrag te zien
  __switches:
    - name: state
      label: Open/sluit
  menuItems:
    - label: Home
      active: true
    - label: Actueel
    - label: Kalender
    - label: Zelf aan de slag
    - label: Documenten
    - label: Over ons
      count: 12
    - label: Wetgeving
  modifier: main
  items:
  - label: Home
    active: true
  - label: Vergunningcheck
  - label: Aanvragen
  - label: Regels op de kaart
  - label: Mijn Omgevingsloket
  collapsed: true
variants:
  - name: open
    context:
      __title: Menu open
      __explanation: Verklein de viewport om het responsive menu open te zien
      __switches: null
      collapsed: false
