status: ready
collated: true
context:
  __title: default
  label: Home
  url: "#"
variants:
  - name: download
    context:
      __title: download
      label: Download Afvalkalender 2017
      url: afvalkalender.pdf
      modifier: download
  - name: extern
    context:
      __title: extern
      label: Een link naar Google
      url: http://www.google.nl
      modifier: extern
  - name: icon
    context:
      __title: icon
      icon: search
      iconOnly: true
      label: Product zoeken
  - name: label
    context:
      __title: label
      label: Product zoeken
  - name: iconLabel
    context:
      __title: icon label
      icon: search
      label: Product zoeken
