status: ready
id: toggle-info
collated: true
context:
  __title: default
  infoOpen: false
  infoButtonLabel: Toelichting bij optie
variants:
- name: toggle-info-active
  context:
    __title: open
    infoOpen: true
- name: toggle-info-secondary
  context:
    __title: secondary
    infoSecondary: true
- name: toggle-info-secondary-active
  context:
    __title: secondary open
    infoSecondary: true
    infoOpen: true

