status: ready
collated: true
label: Navigations
context:
  __title: 'Primary'
  __explanation: Verklein de viewport en gebruik de checkbox om het responsive gedrag te zien
  __switches:
    - name: state
      label: Open/sluit
  modifier: main
  items:
  - label: Home
    active: true
  - label: Vergunningcheck
  - label: Aanvragen
  - label: Regels op de kaart
  - label: Mijn Omgevingsloket
  collapsed: true
variants:
  - name: secondary
    context:
      __title: 'Secondary'
      __explanation: null
      __switches: null
      modifier: sub
      items:
      - label: Deze locatie
        active: true
      - label: Regels
      - label: Overige informatie
