status: ready
default: tabs
collated: true
label: Navigations
context:
  __title: Hoofdnavigatie
  modifier: main
  items:
  - label: Home
    active: true
  - label: Actueel
  - label: Kalender
  - label: Zelf aan de slag
  - label: Documenten
  - label: Over ons
  - label: Wetgeving
variants:
  - name: subnavigation
    context:
      __title: Subnavigatie
      modifier: sub
      items:
      - label: Deze locatie
        active: true
      - label: Regels
      - label: Overige informatie

