notes: |
  Dit component ondersteund twee verschillende manieren voor het maken van een upload knop:
  * Een `input[type="file"]` met een `label` element
  * Een `button` element

  Zie de comments in de HTML. Het gebruik van een `input[type="file"]` is semantisch correcter en voorkomt mogelijke _clickjacking_ warnings in Firefox. Het afhandelen van de upload kan aan `onchange` worden gehangen.

  https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/
collated: true
context:
  __title: default
  id: input-file-default
  label: Files - Default
variants:
- name: input-file-required
  context:
    __title: required
    id: input-file-required
    label: Files - Required
    required: true
- name: input-file-invalid
  context:
    __title: invalid
    id: input-file-invalid
    label: Files - Invalid
    required: true
    state: invalid
    errorText: Voeg een document toe.
- name: input-file-valid
  context:
    __title: valid
    id: input-file-valid
    label: Files - Valid
    required: true
    state: valid
    files:
    - filename: Bestandsnaam.pdf
- name: input-file-disabled
  context:
    __title: disabled
    id: input-file-disabled
    label: Files - Disabled
    required: true
    disabled: true
- name: input-file-explanation
  context:
    __title: explanation
    id: input-file-explanation
    label: Files - Explanation
    required: true
    infoOpen: true
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
- name: input-file-confidential
  context:
    __title: confidential
    id: input-file-confidential
    label: Files - Confidential
    required: true
    files:
    - filename: Bestandsnaam.pdf
    - filename: Bestandsnaam.pdf
      confidential: true
- name: input-file-description
  context:
    __title: Description (deprecated)
    id: input-file-description
    label: Files - Description (Deprecated)
    required: true
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est. Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius. Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
