notes: |
  'Attribuut `@rows` is optioneel'
status: ready
collated: true
context:
  __title: default
  id: input-textarea
  label: Group textarea - Default
variants:
- name: input-textarea-invalid
  context:
    __title: Ongeldig
    __explanation:
    - Indien een textarea ongeldig is, dient er een <code>.dso-invalid</code> class
      gezet te worden op de div met de class <code>.dso-textarea</code>.
    id: input-textarea-invalid
    label: Group textarea - Invalid
    required: true
    helpText: Vul een geldige tekst in
    state: invalid
    errorText: Vul dit veld in.
- name: input-textarea-valid
  context:
    __title: Geldig
    __explanation:
    - Indien een textarea ongeldig was en valide wordt gemaakt, dient
      de <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-textarea-valid
    label: Group textarea - Valid
    required: true
    state: valid
    helpText: Minimaal 6 tekens waarvan 1 leesteken
    value: Ik heb wat ingevuld
- name: input-textarea-rows6
  context:
    __title: Een textarea met 6 rijen
    __explanation: Een textarea zonder <code>rows</code> attribuut krijgt een standaard hoogte. De implementator kan met <code>rows</code> de hoogte van de textarea sturen
    id: input-textarea-rows6
    rows: 6
- name: input-textarea-placeholder
  context:
    __title: Placeholder
    id: input-textarea-placeholder
    placeholder: Bijvoorbeeld; vragen over de toolkit
    required: true
- name: input-textarea-disabled
  context:
    __title: Disabled
    id: input-textarea-disabled
    label: Group textarea - Disabled
    required: true
    disabled: true
- name: input-textarea-readonly
  context:
    __title: Readonly
    id: input-textarea-readonly
    label: Group textarea - Readonly
    required: true
    readonly: true
- name: input-textarea-infobutton-open
  context:
    __title: Infobutton uitgeklapt
    __explanation:
    - Toelichting uitgeklapt
    id: input-textarea-infobutton-open
    required: true
    infoOpen: true
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      <h4>Toelichting bij vraag: "Wilt u nog wat kwijt?"</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    infoTextDeprecated: |
      <h4>Toelichting bij vraag: "Wilt u nog wat kwijt?" - BINNENKORT DEPRECATED</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
