status: ready
collated: true
context:
  __title: default
  id: search-bar
  label: Group search bar - Default
  searchBar:
    id: search-bar
    type: text
    clearButton: true
    hideSearchButton: true
    icon: true
    placeholder: Bv. boomkap
variants:
- name: search-bar-infobutton
  context:
    __title: Infobutton ingeklapt
    __explanation:
      - Toelichting ingeklapt
    id: search-bar-infobutton
    infoOpen: false
    infoButtonLabel: Toelichting bij zoekveld
    infoText: |
      Closed
    searchBar:
      id: search-bar-infobutton
      type: text
      clearButton: true
      hideSearchButton: true
      icon: true
      placeholder: Bv. boomkap
- name: search-bar-infobutton-expanded
  context:
    __title: Infobutton uitgeklapt
    __explanation:
      - Toelichting uitgeklapt
    id: search-bar-infobutton-expanded
    infoOpen: true
    infoButtonLabel: Toelichting bij zoekveld
    infoText: |
      <h4>Toelichting bij vraag: "Activiteit"</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    infoTextDeprecated: |
      <h4>Toelichting bij vraag: "Activiteit" - BINNENKORT DEPRECATED</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    searchBar:
      id: search-bar-infobutton-expanded
      type: text
      clearButton: true
      hideSearchButton: true
      icon: true
      placeholder: Bv. boomkap
- name: search-bar-error
  context:
    __title: Foutmelding
    __explanation:
      - Indien een input ongeldig is, dient er een <code>.dso-invalid</code> class gezet te worden op de div met de class <code>.dso-input</code>.
    id: search-bar-error
    label: Group search bar - Ongeldig
    state: invalid
    errorText: Vul dit veld in.
    searchBar:
      id: search-bar-error
      type: text
      clearButton: true
      hideSearchButton: true
      icon: true
      placeholder: Bv. boomkap
- name: search-bar-help
  context:
    __title: Help tekst
    __explanation:
      - Indien een input ongeldig is, dient er een <code>.dso-invalid</code> class gezet te worden op de div met de class <code>.dso-input</code>.
    id: search-bar-help
    helpText: 'Type en selecteer de activiteit'
    searchBar:
      id: search-bar-help
      type: text
      clearButton: true
      hideSearchButton: true
      icon: true
      placeholder: Bv. boomkap
