status: ready
collated: true
context:
  __title: default
  label: Default
  id: default
  type: stepper
  count: 99
  minusButtonLabel: Aantal verlagen
  plusButtonLabel: Aantal verhogen
variants:
- name: input-number-inactive
  context:
    __title: Inactive
    label: Inactive input stepper
    id: inactive
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
- name: input-number-minimum-limit
  context:
    __title: Minimum limit (optional)
    label: Input stepper with minimum limit
    id: minimum-limit
    count: 0
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
- name: input-stepper-maximum-limit
  context:
    __title: Maximum limit (optional)
    label: Input stepper with maximum limit
    id: maximum-limit
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
- name: no-label
  context:
    __title: no label
    label: null
    id: no-label
