meta:
  webComponent: true
  markup: true
notes: |
  De progress indicator is er in drie groottes (small: 24px, medium: 32px, large: 48px). 
status: ready
collated: true
context:
  __title: Spinner 24px groot
  status: Een moment geduld alstublieft.
  size: small
variants:
- name: spinner-medium-infinite
  context:
    __title: Spinner 32px groot
    size: medium
- name: spinner-large-infinite
  context:
    __title: Spinner 48px groot
    size: large

