label: Progress Indicator (Web Component)
meta:
  webComponent: dso-progress-indicator
notes: |
  De progress indicator is er in drie groottes (`small`: 24px, `medium`: 32px, `large`: 48px);

  * toevoeging attribute `block` zorgt voor horizontaal en verticaal gecentreerde progress-indicator;
  * icm. size `small` zorgt dit voor een (afhankelijk van de inhoud) minimaal 48px hoge progress indicator;
  * icm. size `medium` zorgt dit voor een (afhankelijk van de inhoud) minimaal 64px hoge progress indicator;
  * icm. size `large` zorgt dit voor een (afhankelijk van de inhoud) minimaal 96px hoge progress indicator;

status: ready
collated: true
context:
  __title: Spinner small (24px)
  label: "Resultaten laden: een moment geduld alstublieft."
  size: small
variants:
- name: spinner-medium-infinite
  context:
    __title: Spinner medium (32px)
    size: medium
- name: spinner-large-infinite
  context:
    __title: Spinner large (48px)
    size: large
- name: spinner-small-block
  context:
    __title: Spinner small - gecentreerd blok
    size: small
    block: true
- name: spinner-large-block
  context:
    __title: Spinner large - gecentreerd blok
    size: large
    block: true
