notes: Externe links krijgen de class `extern` en een `target="_blank"`
status: ready
collated: true
label: Link
context:
  label: Home
  url: "#"
variants:
  - name: download
    context:
      label: Afvalkalender 2017
      url: afvalkalender.pdf
      modifier: download
  - name: extern
    context:
      label: Een link naar Google met een extreem lang label zodat hij gaat wrappen en het icoon goed uitgelijnd blijft.
      url: http://www.google.nl
      modifier: extern
  - name: icon
    context:
      icon: fas fa-search
      iconOnly: true
      label: Zoeken
  - name: label
    context:
      label: Zoeken
  - name: iconLabel
    context:
      icon: fas fa-search
      label: zoeken
  - name: iconBadge
    context:
      icon: fas fa-search
      iconOnly: true
      label: zoeken
      badge:
        label: 4
  - name: iconLabelBadge
    context:
      icon: fas fa-search
      label: zoeken
      badge:
        label: 4
